#!/usr/bin/env node
/**
 * scripts/configure-bin.js
 *
 * Runs before every build (see package.json "prebuild"). Reads CLI_COMMAND_NAME from
 * .env (falling back to "devx" if .env or the variable is missing), then:
 *   1. Rewrites package.json's "bin" field to that command name.
 *   2. Regenerates src/generated/brand.ts so runtime code (help text, log prefixes,
 *      "devx -version") reflects the same name and the current package.json version.
 *
 * This lets the CLI be re-branded/renamed without touching any TypeScript source —
 * just edit .env and rebuild.
 */
const fs = require("fs");
const path = require("path");

const ROOT = path.resolve(__dirname, "..");
const ENV_PATH = path.join(ROOT, ".env");
const PACKAGE_JSON_PATH = path.join(ROOT, "package.json");
const BRAND_OUTPUT_PATH = path.join(ROOT, "src", "generated", "brand.ts");

const DEFAULT_COMMAND_NAME = "devx";
const BRAND_NAME = "Software Engineer Agentic CLI";
const BRAND_ABBREVIATION = "SEA CLI";

function parseEnvFile(filePath) {
  const result = {};
  if (!fs.existsSync(filePath)) return result;
  const lines = fs.readFileSync(filePath, "utf-8").split("\n");
  for (const line of lines) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith("#")) continue;
    const eq = trimmed.indexOf("=");
    if (eq === -1) continue;
    const key = trimmed.slice(0, eq).trim();
    const value = trimmed.slice(eq + 1).trim().replace(/^["']|["']$/g, "");
    result[key] = value;
  }
  return result;
}

function isValidCommandName(name) {
  // Keep it to sane shell-command characters: letters, digits, dashes, underscores.
  return /^[a-zA-Z][a-zA-Z0-9_-]*$/.test(name);
}

function main() {
  const env = parseEnvFile(ENV_PATH);
  let commandName = (env.CLI_COMMAND_NAME || DEFAULT_COMMAND_NAME).trim();

  if (!isValidCommandName(commandName)) {
    console.warn(
      `configure-bin: CLI_COMMAND_NAME "${commandName}" isn't a valid command name; falling back to "${DEFAULT_COMMAND_NAME}".`
    );
    commandName = DEFAULT_COMMAND_NAME;
  }

  // 1. Update package.json's bin field (and keep package.json's own "name" in sync too).
  const pkg = JSON.parse(fs.readFileSync(PACKAGE_JSON_PATH, "utf-8"));
  pkg.bin = { [commandName]: "dist/cli/index.js" };
  fs.writeFileSync(PACKAGE_JSON_PATH, JSON.stringify(pkg, null, 2) + "\n", "utf-8");

  // 2. Regenerate the brand module consumed at runtime.
  fs.mkdirSync(path.dirname(BRAND_OUTPUT_PATH), { recursive: true });
  const brandSource = `/**
 * GENERATED FILE — do not edit by hand.
 * Produced by scripts/configure-bin.js from .env + package.json during \`npm run build\`.
 * To rename the CLI, edit CLI_COMMAND_NAME in .env and rebuild; do not edit this file directly.
 */
export const CLI_COMMAND_NAME = ${JSON.stringify(commandName)};
export const BRAND_NAME = ${JSON.stringify(BRAND_NAME)};
export const BRAND_ABBREVIATION = ${JSON.stringify(BRAND_ABBREVIATION)};
export const VERSION = ${JSON.stringify(pkg.version)};
`;
  fs.writeFileSync(BRAND_OUTPUT_PATH, brandSource, "utf-8");

  console.log(`configure-bin: command name = "${commandName}", version = ${pkg.version}`);
}

main();
